"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LocationType = exports.CityName = exports.LocationName = void 0;
/** Names of all locations */
var LocationName;
(function (LocationName) {
    LocationName["AevumAeroCorp"] = "AeroCorp";
    LocationName["AevumBachmanAndAssociates"] = "Bachman & Associates";
    LocationName["AevumClarkeIncorporated"] = "Clarke Incorporated";
    LocationName["AevumCrushFitnessGym"] = "Crush Fitness Gym";
    LocationName["AevumECorp"] = "ECorp";
    LocationName["AevumFulcrumTechnologies"] = "Fulcrum Technologies";
    LocationName["AevumGalacticCybersystems"] = "Galactic Cybersystems";
    LocationName["AevumNetLinkTechnologies"] = "NetLink Technologies";
    LocationName["AevumPolice"] = "Aevum Police Headquarters";
    LocationName["AevumRhoConstruction"] = "Rho Construction";
    LocationName["AevumSnapFitnessGym"] = "Snap Fitness Gym";
    LocationName["AevumSummitUniversity"] = "Summit University";
    LocationName["AevumWatchdogSecurity"] = "Watchdog Security";
    LocationName["AevumCasino"] = "Iker Molina Casino";
    LocationName["ChongqingKuaiGongInternational"] = "KuaiGong International";
    LocationName["ChongqingSolarisSpaceSystems"] = "Solaris Space Systems";
    LocationName["ChongqingChurchOfTheMachineGod"] = "Church of the Machine God";
    LocationName["Sector12AlphaEnterprises"] = "Alpha Enterprises";
    LocationName["Sector12BladeIndustries"] = "Blade Industries";
    LocationName["Sector12CIA"] = "Central Intelligence Agency";
    LocationName["Sector12CarmichaelSecurity"] = "Carmichael Security";
    LocationName["Sector12CityHall"] = "Sector-12 City Hall";
    LocationName["Sector12DeltaOne"] = "DeltaOne";
    LocationName["Sector12FoodNStuff"] = "FoodNStuff";
    LocationName["Sector12FourSigma"] = "Four Sigma";
    LocationName["Sector12IcarusMicrosystems"] = "Icarus Microsystems";
    LocationName["Sector12IronGym"] = "Iron Gym";
    LocationName["Sector12JoesGuns"] = "Joe's Guns";
    LocationName["Sector12MegaCorp"] = "MegaCorp";
    LocationName["Sector12NSA"] = "National Security Agency";
    LocationName["Sector12PowerhouseGym"] = "Powerhouse Gym";
    LocationName["Sector12RothmanUniversity"] = "Rothman University";
    LocationName["Sector12UniversalEnergy"] = "Universal Energy";
    LocationName["NewTokyoDefComm"] = "DefComm";
    LocationName["NewTokyoGlobalPharmaceuticals"] = "Global Pharmaceuticals";
    LocationName["NewTokyoNoodleBar"] = "Noodle Bar";
    LocationName["NewTokyoVitaLife"] = "VitaLife";
    LocationName["NewTokyoArcade"] = "Arcade";
    LocationName["IshimaNovaMedical"] = "Nova Medical";
    LocationName["IshimaOmegaSoftware"] = "Omega Software";
    LocationName["IshimaStormTechnologies"] = "Storm Technologies";
    LocationName["IshimaGlitch"] = "0x6C1";
    LocationName["VolhavenCompuTek"] = "CompuTek";
    LocationName["VolhavenHeliosLabs"] = "Helios Labs";
    LocationName["VolhavenLexoCorp"] = "LexoCorp";
    LocationName["VolhavenMilleniumFitnessGym"] = "Millenium Fitness Gym";
    LocationName["VolhavenNWO"] = "NWO";
    LocationName["VolhavenOmniTekIncorporated"] = "OmniTek Incorporated";
    LocationName["VolhavenOmniaCybersystems"] = "Omnia Cybersystems";
    LocationName["VolhavenSysCoreSecurities"] = "SysCore Securities";
    LocationName["VolhavenZBInstituteOfTechnology"] = "ZB Institute of Technology";
    LocationName["Hospital"] = "Hospital";
    LocationName["Slums"] = "The Slums";
    LocationName["TravelAgency"] = "Travel Agency";
    LocationName["WorldStockExchange"] = "World Stock Exchange";
    LocationName["Void"] = "The Void";
})(LocationName || (exports.LocationName = LocationName = {}));
/** Names of all cities */
var CityName;
(function (CityName) {
    CityName["Aevum"] = "Aevum";
    CityName["Chongqing"] = "Chongqing";
    CityName["Sector12"] = "Sector-12";
    CityName["NewTokyo"] = "New Tokyo";
    CityName["Ishima"] = "Ishima";
    CityName["Volhaven"] = "Volhaven";
})(CityName || (exports.CityName = CityName = {}));
var LocationType;
(function (LocationType) {
    LocationType["Company"] = "Company";
    LocationType["Gym"] = "Gym";
    LocationType["Hospital"] = "Hospital";
    LocationType["Slums"] = "Slums";
    LocationType["Special"] = "Special";
    LocationType["StockMarket"] = "Stock Market";
    LocationType["TechVendor"] = "Tech Vendor";
    LocationType["TravelAgency"] = "Travel Agency";
    LocationType["University"] = "University";
    LocationType["Casino"] = "Casino";
})(LocationType || (exports.LocationType = LocationType = {}));
