"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CodingContractName = void 0;
var CodingContractName;
(function (CodingContractName) {
    CodingContractName["FindLargestPrimeFactor"] = "Find Largest Prime Factor";
    CodingContractName["SubarrayWithMaximumSum"] = "Subarray with Maximum Sum";
    CodingContractName["TotalWaysToSum"] = "Total Ways to Sum";
    CodingContractName["TotalWaysToSumII"] = "Total Ways to Sum II";
    CodingContractName["SpiralizeMatrix"] = "Spiralize Matrix";
    CodingContractName["ArrayJumpingGame"] = "Array Jumping Game";
    CodingContractName["ArrayJumpingGameII"] = "Array Jumping Game II";
    CodingContractName["MergeOverlappingIntervals"] = "Merge Overlapping Intervals";
    CodingContractName["GenerateIPAddresses"] = "Generate IP Addresses";
    CodingContractName["AlgorithmicStockTraderI"] = "Algorithmic Stock Trader I";
    CodingContractName["AlgorithmicStockTraderII"] = "Algorithmic Stock Trader II";
    CodingContractName["AlgorithmicStockTraderIII"] = "Algorithmic Stock Trader III";
    CodingContractName["AlgorithmicStockTraderIV"] = "Algorithmic Stock Trader IV";
    CodingContractName["MinimumPathSumInATriangle"] = "Minimum Path Sum in a Triangle";
    CodingContractName["UniquePathsInAGridI"] = "Unique Paths in a Grid I";
    CodingContractName["UniquePathsInAGridII"] = "Unique Paths in a Grid II";
    CodingContractName["ShortestPathInAGrid"] = "Shortest Path in a Grid";
    CodingContractName["SanitizeParenthesesInExpression"] = "Sanitize Parentheses in Expression";
    CodingContractName["FindAllValidMathExpressions"] = "Find All Valid Math Expressions";
    CodingContractName["HammingCodesIntegerToEncodedBinary"] = "HammingCodes: Integer to Encoded Binary";
    CodingContractName["HammingCodesEncodedBinaryToInteger"] = "HammingCodes: Encoded Binary to Integer";
    CodingContractName["Proper2ColoringOfAGraph"] = "Proper 2-Coloring of a Graph";
    CodingContractName["CompressionIRLECompression"] = "Compression I: RLE Compression";
    CodingContractName["CompressionIILZDecompression"] = "Compression II: LZ Decompression";
    CodingContractName["CompressionIIILZCompression"] = "Compression III: LZ Compression";
    CodingContractName["EncryptionICaesarCipher"] = "Encryption I: Caesar Cipher";
    CodingContractName["EncryptionIIVigenereCipher"] = "Encryption II: Vigen\u00E8re Cipher";
    CodingContractName["SquareRoot"] = "Square Root";
    CodingContractName["TotalPrimesInRange"] = "Total Number of Primes";
})(CodingContractName || (exports.CodingContractName = CodingContractName = {}));
