"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FactionDiscovery = exports.FactionName = void 0;
var FactionName;
(function (FactionName) {
    FactionName["Illuminati"] = "Illuminati";
    FactionName["Daedalus"] = "Daedalus";
    FactionName["TheCovenant"] = "The Covenant";
    FactionName["ECorp"] = "ECorp";
    FactionName["MegaCorp"] = "MegaCorp";
    FactionName["BachmanAndAssociates"] = "Bachman & Associates";
    FactionName["BladeIndustries"] = "Blade Industries";
    FactionName["NWO"] = "NWO";
    FactionName["ClarkeIncorporated"] = "Clarke Incorporated";
    FactionName["OmniTekIncorporated"] = "OmniTek Incorporated";
    FactionName["FourSigma"] = "Four Sigma";
    FactionName["KuaiGongInternational"] = "KuaiGong International";
    FactionName["FulcrumSecretTechnologies"] = "Fulcrum Secret Technologies";
    FactionName["BitRunners"] = "BitRunners";
    FactionName["TheBlackHand"] = "The Black Hand";
    FactionName["NiteSec"] = "NiteSec";
    FactionName["Aevum"] = "Aevum";
    FactionName["Chongqing"] = "Chongqing";
    FactionName["Ishima"] = "Ishima";
    FactionName["NewTokyo"] = "New Tokyo";
    FactionName["Sector12"] = "Sector-12";
    FactionName["Volhaven"] = "Volhaven";
    FactionName["SpeakersForTheDead"] = "Speakers for the Dead";
    FactionName["TheDarkArmy"] = "The Dark Army";
    FactionName["TheSyndicate"] = "The Syndicate";
    FactionName["Silhouette"] = "Silhouette";
    FactionName["Tetrads"] = "Tetrads";
    FactionName["SlumSnakes"] = "Slum Snakes";
    FactionName["Netburners"] = "Netburners";
    FactionName["TianDiHui"] = "Tian Di Hui";
    FactionName["CyberSec"] = "CyberSec";
    FactionName["Bladeburners"] = "Bladeburners";
    FactionName["ChurchOfTheMachineGod"] = "Church of the Machine God";
    FactionName["ShadowsOfAnarchy"] = "Shadows of Anarchy";
})(FactionName || (exports.FactionName = FactionName = {}));
var FactionDiscovery;
(function (FactionDiscovery) {
    FactionDiscovery["unknown"] = "unknown";
    FactionDiscovery["rumored"] = "rumored";
    FactionDiscovery["known"] = "known";
})(FactionDiscovery || (exports.FactionDiscovery = FactionDiscovery = {}));
