"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JobField = exports.JobName = exports.ClassType = exports.GymType = exports.UniversityClassType = exports.FactionWorkType = void 0;
var FactionWorkType;
(function (FactionWorkType) {
    FactionWorkType["hacking"] = "hacking";
    FactionWorkType["field"] = "field";
    FactionWorkType["security"] = "security";
})(FactionWorkType || (exports.FactionWorkType = FactionWorkType = {}));
var UniversityClassType;
(function (UniversityClassType) {
    UniversityClassType["computerScience"] = "Computer Science";
    UniversityClassType["dataStructures"] = "Data Structures";
    UniversityClassType["networks"] = "Networks";
    UniversityClassType["algorithms"] = "Algorithms";
    UniversityClassType["management"] = "Management";
    UniversityClassType["leadership"] = "Leadership";
})(UniversityClassType || (exports.UniversityClassType = UniversityClassType = {}));
//Uses skill short codes to allow easier fuzzy matching with player input
var GymType;
(function (GymType) {
    GymType["strength"] = "str";
    GymType["defense"] = "def";
    GymType["dexterity"] = "dex";
    GymType["agility"] = "agi";
})(GymType || (exports.GymType = GymType = {}));
exports.ClassType = { ...UniversityClassType, ...GymType };
// Can split this later
var JobName;
(function (JobName) {
    JobName["software0"] = "Software Engineering Intern";
    JobName["software1"] = "Junior Software Engineer";
    JobName["software2"] = "Senior Software Engineer";
    JobName["software3"] = "Lead Software Developer";
    JobName["software4"] = "Head of Software";
    JobName["software5"] = "Head of Engineering";
    JobName["software6"] = "Vice President of Technology";
    JobName["software7"] = "Chief Technology Officer";
    JobName["IT0"] = "IT Intern";
    JobName["IT1"] = "IT Analyst";
    JobName["IT2"] = "IT Manager";
    JobName["IT3"] = "Systems Administrator";
    JobName["securityEng"] = "Security Engineer";
    JobName["networkEng0"] = "Network Engineer";
    JobName["networkEng1"] = "Network Administrator";
    JobName["business0"] = "Business Intern";
    JobName["business1"] = "Business Analyst";
    JobName["business2"] = "Business Manager";
    JobName["business3"] = "Operations Manager";
    JobName["business4"] = "Chief Financial Officer";
    JobName["business5"] = "Chief Executive Officer";
    JobName["security0"] = "Security Guard";
    JobName["security1"] = "Security Officer";
    JobName["security2"] = "Security Supervisor";
    JobName["security3"] = "Head of Security";
    JobName["agent0"] = "Field Agent";
    JobName["agent1"] = "Secret Agent";
    JobName["agent2"] = "Special Operative";
    JobName["employee"] = "Employee";
    JobName["employeePT"] = "Part-time Employee";
    JobName["waiter"] = "Waiter";
    JobName["waiterPT"] = "Part-time Waiter";
    JobName["softwareConsult0"] = "Software Consultant";
    JobName["softwareConsult1"] = "Senior Software Consultant";
    JobName["businessConsult0"] = "Business Consultant";
    JobName["businessConsult1"] = "Senior Business Consultant";
})(JobName || (exports.JobName = JobName = {}));
var JobField;
(function (JobField) {
    JobField["software"] = "Software";
    JobField["softwareConsultant"] = "Software Consultant";
    JobField["it"] = "IT";
    JobField["securityEngineer"] = "Security Engineer";
    JobField["networkEngineer"] = "Network Engineer";
    JobField["business"] = "Business";
    JobField["businessConsultant"] = "Business Consultant";
    JobField["security"] = "Security";
    JobField["agent"] = "Agent";
    JobField["employee"] = "Employee";
    JobField["partTimeEmployee"] = "Part-time Employee";
    JobField["waiter"] = "Waiter";
    JobField["partTimeWaiter"] = "Part-time Waiter";
})(JobField || (exports.JobField = JobField = {}));
