"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HashManager = void 0;
/**
 * This is a central class for storing and managing the player's hashes,
 * which are generated by Hacknet Servers
 *
 * It is also used to keep track of what upgrades the player has bought with
 * his hashes, and contains method for grabbing the data/multipliers from
 * those upgrades
 */
const HashUpgrades_1 = require("./HashUpgrades");
const JSONReviver_1 = require("../utils/JSONReviver");
const Enums_1 = require("./Enums");
class HashManager {
    constructor() {
        // Max number of hashes this can hold. Equal to the sum of capacities of
        // all Hacknet Servers
        this.capacity = 0;
        // Number of hashes currently in storage
        this.hashes = 0;
        // Map of Hash Upgrade Name -> levels in that upgrade
        this.upgrades = {};
        for (const name of Object.keys(HashUpgrades_1.HashUpgrades)) {
            this.upgrades[name] = 0;
        }
    }
    /** Generic helper function for getting a multiplier from a HashUpgrade */
    getMult(upgName) {
        const upg = HashUpgrades_1.HashUpgrades[upgName];
        const currLevel = this.upgrades[upgName];
        if (upg == null || currLevel == null) {
            console.error(`Could not find Hash Study upgrade`);
            return 1;
        }
        return 1 + (upg.value * currLevel) / 100;
    }
    /** One of the Hash upgrades improves studying. This returns that multiplier */
    getStudyMult() {
        const upgName = Enums_1.HashUpgradeEnum.ImproveStudying;
        return this.getMult(upgName);
    }
    /** One of the Hash upgrades improves gym training. This returns that multiplier */
    getTrainingMult() {
        const upgName = Enums_1.HashUpgradeEnum.ImproveGymTraining;
        return this.getMult(upgName);
    }
    getUpgrade(upgName) {
        const upg = HashUpgrades_1.HashUpgrades[upgName];
        if (!upg) {
            console.error(`Invalid Upgrade Name given to HashManager.getUpgrade(): ${upgName}`);
            return null;
        }
        return upg;
    }
    /** Get the cost (in hashes) of an upgrade */
    getUpgradeCost(upgName, count = 1) {
        const upg = this.getUpgrade(upgName);
        const currLevel = this.upgrades[upgName];
        if (upg == null || currLevel == null) {
            console.error(`Invalid Upgrade Name given to HashManager.getUpgradeCost(): ${upgName}`);
            return Infinity;
        }
        return upg.getCost(currLevel, count);
    }
    prestige() {
        for (const name of Object.keys(HashUpgrades_1.HashUpgrades)) {
            this.upgrades[name] = 0;
        }
        this.hashes = 0;
        // When prestiging, player's hacknet nodes are always reset. So capacity = 0
        this.updateCapacity(0);
    }
    /** Reverts an upgrade and refunds the hashes used to buy it */
    refundUpgrade(upgName, count = 1) {
        const upg = HashUpgrades_1.HashUpgrades[upgName];
        // Reduce the level first, so we get the right cost
        this.upgrades[upgName] -= count;
        const currLevel = this.upgrades[upgName];
        if (upg == null || currLevel == null || currLevel < 0) {
            console.error(`Invalid Upgrade Name given to HashManager.upgrade(): ${upgName}`);
            return;
        }
        const cost = upg.getCost(currLevel, count);
        this.hashes += cost;
    }
    /**
     * Stores the given hashes, capping at capacity
     * @param numHashes The number of hashes to increment
     * @returns The number of wasted hashes (over capacity)
     */
    storeHashes(numHashes) {
        this.hashes += numHashes;
        let wastedHashes = this.hashes;
        this.hashes = Math.min(this.hashes, this.capacity);
        wastedHashes -= this.hashes;
        return wastedHashes;
    }
    updateCapacity(newCap) {
        if (newCap < 0) {
            this.capacity = 0;
        }
        this.capacity = Math.max(newCap, 0);
    }
    /**
     * Returns boolean indicating whether or not the upgrade was successfully purchased.
     * Note that this function does NOT actually implement the effect.
     */
    upgrade(upgName, count = 1) {
        const upg = HashUpgrades_1.HashUpgrades[upgName];
        if (upg == null) {
            return { success: false, message: `Invalid Upgrade Name given to HashManager.upgrade(): ${upgName}` };
        }
        const cost = this.getUpgradeCost(upgName, count);
        if (this.hashes < cost) {
            return { success: false, message: "Not enough hashes" };
        }
        this.hashes -= cost;
        this.upgrades[upgName] += count;
        return { success: true };
    }
    //Serialize the current object to a JSON save state.
    toJSON() {
        return (0, JSONReviver_1.Generic_toJSON)("HashManager", this);
    }
    // Initializes a HashManager object from a JSON save state.
    static fromJSON(value) {
        return (0, JSONReviver_1.Generic_fromJSON)(HashManager, value.data);
    }
}
exports.HashManager = HashManager;
JSONReviver_1.constructorsForReviver.HashManager = HashManager;
