"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LiteratureName = void 0;
var LiteratureName;
(function (LiteratureName) {
    LiteratureName["HackersStartingHandbook"] = "hackers-starting-handbook.lit";
    LiteratureName["CorporationManagementHandbook"] = "corporation-management-handbook.lit";
    LiteratureName["HistoryOfSynthoids"] = "history-of-synthoids.lit";
    LiteratureName["AGreenTomorrow"] = "A-Green-Tomorrow.lit";
    LiteratureName["AlphaOmega"] = "alpha-omega.lit";
    LiteratureName["SimulatedReality"] = "simulated-reality.lit";
    LiteratureName["BeyondMan"] = "beyond-man.lit";
    LiteratureName["BrighterThanTheSun"] = "brighter-than-the-sun.lit";
    LiteratureName["DemocracyIsDead"] = "democracy-is-dead.lit";
    LiteratureName["Sector12Crime"] = "sector-12-crime.lit";
    LiteratureName["ManAndMachine"] = "man-and-machine.lit";
    LiteratureName["SecretSocieties"] = "secret-societies.lit";
    LiteratureName["TheFailedFrontier"] = "the-failed-frontier.lit";
    LiteratureName["CodedIntelligence"] = "coded-intelligence.lit";
    LiteratureName["SyntheticMuscles"] = "synthetic-muscles.lit";
    LiteratureName["TensionsInTechRace"] = "tensions-in-tech-race.lit";
    LiteratureName["CostOfImmortality"] = "cost-of-immortality.lit";
    LiteratureName["TheHiddenWorld"] = "the-hidden-world.lit";
    LiteratureName["TheNewGod"] = "the-new-god.lit";
    LiteratureName["NewTriads"] = "new-triads.lit";
    LiteratureName["TheSecretWar"] = "the-secret-war.lit";
})(LiteratureName || (exports.LiteratureName = LiteratureName = {}));
