import { CorpResearchName, CorpSmartSupplyOption } from "@nsdefs";
import { Corporation } from "./Corporation";
import { Division } from "./Division";
import { OfficeSpace } from "./OfficeSpace";
import { Material } from "./Material";
import { Product } from "./Product";
import { Warehouse } from "./Warehouse";
import { FactionName, IndustryType } from "@enums";
import { CityName } from "@enums";
import { PositiveInteger, Result } from "../types";
export declare function createCorporation(corporationName: string, selfFund: boolean, restart: boolean): Result;
export declare function createDivision(corporation: Corporation, industry: IndustryType, name: string): void;
export declare function removeDivision(corporation: Corporation, name: string): number;
export declare function purchaseOffice(corporation: Corporation, division: Division, city: CityName): void;
export declare function issueDividends(corporation: Corporation, rate: number): void;
export declare function goPublic(corporation: Corporation, numShares: number): void;
export declare function issueNewShares(corporation: Corporation, amount: number): [profit: number, amount: number, privateShares: number];
export declare function acceptInvestmentOffer(corporation: Corporation): void;
export declare function convertPriceString(price: string): string;
export declare function convertAmountString(amount: string): string;
export declare function sellMaterial(material: Material, amount: string, price: string): void;
export declare function sellProduct(product: Product, city: CityName, amt: string, price: string, all: boolean): void;
export declare function setSmartSupply(warehouse: Warehouse, smartSupply: boolean): void;
export declare function setSmartSupplyOption(warehouse: Warehouse, material: Material, useOption: CorpSmartSupplyOption): void;
export declare function buyMaterial(division: Division, material: Material, amt: number): void;
export declare function bulkPurchase(corp: Corporation, division: Division, warehouse: Warehouse, material: Material, amt: number): void;
export declare function sellShares(corporation: Corporation, numShares: number): number;
export declare function buyBackShares(corporation: Corporation, numShares: number): boolean;
export declare function upgradeOfficeSize(corp: Corporation, office: OfficeSpace, increase: PositiveInteger): void;
export declare function buyTea(corp: Corporation, office: OfficeSpace): boolean;
export declare function throwParty(corp: Corporation, office: OfficeSpace, costPerEmployee: number): number;
export declare function purchaseWarehouse(corp: Corporation, division: Division, city: CityName): void;
export declare function upgradeWarehouseCost(level: number, amt: number): number;
export declare function upgradeWarehouse(corp: Corporation, division: Division, warehouse: Warehouse, amt?: number): void;
export declare function hireAdVert(corp: Corporation, division: Division): void;
export declare function makeProduct(corp: Corporation, division: Division, city: CityName, productName: string, designInvest: number, marketingInvest: number): void;
export declare function research(researchingDivision: Division, researchName: CorpResearchName): void;
/** Set a new export for a material. Throw on any invalid input. */
export declare function exportMaterial(targetDivision: Division, targetCity: CityName, material: Material, amount: string): void;
export declare function cancelExportMaterial(divisionName: string, cityName: CityName, material: Material): void;
export declare function limitProductProduction(product: Product, cityName: CityName, quantity: number): void;
export declare function limitMaterialProduction(material: Material, quantity: number): void;
export declare function setMaterialMarketTA1(material: Material, on: boolean): void;
export declare function setMaterialMarketTA2(material: Material, on: boolean): void;
export declare function setProductMarketTA1(product: Product, on: boolean): void;
export declare function setProductMarketTA2(product: Product, on: boolean): void;
export declare function bribe(corporation: Corporation, fundsForBribing: number, factionName: FactionName): Result<{
    reputationGain: number;
}>;
