"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RamCosts = exports.RamCostConstants = void 0;
exports.getRamCost = getRamCost;
const _player_1 = require("@player");
/** Constants for assigning costs to ns functions */
exports.RamCostConstants = {
    Base: 1.6,
    Dom: 25,
    CorporationInfo: 10,
    CorporationAction: 20,
    Max: 1024,
    Hack: 0.1,
    HackAnalyze: 1,
    Grow: 0.15,
    GrowthAnalyze: 1,
    Weaken: 0.15,
    WeakenAnalyze: 1,
    Scan: 0.2,
    RecentScripts: 0.2,
    PortProgram: 0.05,
    Run: 1.0,
    Exec: 1.3,
    Spawn: 2.0,
    Scp: 0.6,
    Kill: 0.5,
    HasRootAccess: 0.05,
    GetHostname: 0.05,
    GetHackingLevel: 0.05,
    GetServer: 0.1,
    GetServerMaxRam: 0.05,
    GetServerUsedRam: 0.05,
    FileExists: 0.1,
    IsRunning: 0.1,
    HacknetNodes: 4.0,
    HNUpgLevel: 0.4,
    HNUpgRam: 0.6,
    HNUpgCore: 0.8,
    GetStock: 2.0,
    BuySellStock: 2.5,
    GetPurchaseServer: 0.25,
    PurchaseServer: 2.25,
    GetPurchasedServerLimit: 0.05,
    GetPurchasedServerMaxRam: 0.05,
    Round: 0.05,
    ReadWrite: 1.0,
    ArbScript: 1.0,
    GetScript: 0.1,
    GetRunningScript: 0.3,
    GetHackTime: 0.05,
    GetFavorToDonate: 0.1,
    CodingContractBase: 10,
    SleeveBase: 4,
    ClearTerminalCost: 0.2,
    GetMoneySourcesCost: 1.0,
    SingularityFn1: 2,
    SingularityFn2: 3,
    SingularityFn3: 5,
    GangApiBase: 4,
    BladeburnerApiBase: 4,
    StanekWidth: 0.4,
    StanekHeight: 0.4,
    StanekCharge: 0.4,
    StanekFragmentDefinitions: 0,
    StanekPlacedFragments: 5,
    StanekClear: 0,
    StanekCanPlace: 0.5,
    StanekPlace: 5,
    StanekFragmentAt: 2,
    StanekDeleteAt: 0.15,
    StanekAcceptGift: 2,
    InfiltrationCalculateDifficulty: 2.5,
    InfiltrationCalculateRewards: 2.5,
    InfiltrationGetInfiltrations: 15,
    CycleTiming: 1,
};
function SF4Cost(cost) {
    return () => {
        if (_player_1.Player.bitNodeN === 4) {
            return cost;
        }
        const sf4 = _player_1.Player.activeSourceFileLvl(4);
        if (sf4 <= 1) {
            return cost * 16;
        }
        if (sf4 === 2) {
            return cost * 4;
        }
        return cost;
    };
}
// Hacknet API
const hacknet = {
    numNodes: 0,
    purchaseNode: 0,
    getPurchaseNodeCost: 0,
    getNodeStats: 0,
    upgradeLevel: 0,
    upgradeRam: 0,
    upgradeCore: 0,
    upgradeCache: 0,
    getLevelUpgradeCost: 0,
    getRamUpgradeCost: 0,
    getCoreUpgradeCost: 0,
    getCacheUpgradeCost: 0,
    numHashes: 0,
    hashCost: 0,
    spendHashes: 0,
    maxNumNodes: 0,
    hashCapacity: 0,
    getHashUpgrades: 0,
    getHashUpgradeLevel: 0,
    getStudyMult: 0,
    getTrainingMult: 0,
};
// Stock API
const stock = {
    getConstants: 0,
    hasWseAccount: 0.05,
    hasTixApiAccess: 0.05,
    has4SData: 0.05,
    has4SDataTixApi: 0.05,
    getBonusTime: 0,
    nextUpdate: exports.RamCostConstants.CycleTiming,
    getSymbols: exports.RamCostConstants.GetStock,
    getPrice: exports.RamCostConstants.GetStock,
    getOrganization: exports.RamCostConstants.GetStock,
    getAskPrice: exports.RamCostConstants.GetStock,
    getBidPrice: exports.RamCostConstants.GetStock,
    getPosition: exports.RamCostConstants.GetStock,
    getMaxShares: exports.RamCostConstants.GetStock,
    getPurchaseCost: exports.RamCostConstants.GetStock,
    getSaleGain: exports.RamCostConstants.GetStock,
    buyStock: exports.RamCostConstants.BuySellStock,
    sellStock: exports.RamCostConstants.BuySellStock,
    buyShort: exports.RamCostConstants.BuySellStock,
    sellShort: exports.RamCostConstants.BuySellStock,
    placeOrder: exports.RamCostConstants.BuySellStock,
    cancelOrder: exports.RamCostConstants.BuySellStock,
    getOrders: exports.RamCostConstants.BuySellStock,
    getVolatility: exports.RamCostConstants.BuySellStock,
    getForecast: exports.RamCostConstants.BuySellStock,
    purchase4SMarketData: exports.RamCostConstants.BuySellStock,
    purchase4SMarketDataTixApi: exports.RamCostConstants.BuySellStock,
    purchaseWseAccount: exports.RamCostConstants.BuySellStock,
    purchaseTixApi: exports.RamCostConstants.BuySellStock,
};
// Singularity API
const singularity = {
    universityCourse: SF4Cost(exports.RamCostConstants.SingularityFn1),
    gymWorkout: SF4Cost(exports.RamCostConstants.SingularityFn1),
    travelToCity: SF4Cost(exports.RamCostConstants.SingularityFn1),
    goToLocation: SF4Cost(exports.RamCostConstants.SingularityFn3),
    purchaseTor: SF4Cost(exports.RamCostConstants.SingularityFn1),
    purchaseProgram: SF4Cost(exports.RamCostConstants.SingularityFn1),
    getCurrentServer: SF4Cost(exports.RamCostConstants.SingularityFn1),
    getCompanyPositionInfo: SF4Cost(exports.RamCostConstants.SingularityFn1),
    getCompanyPositions: SF4Cost(exports.RamCostConstants.SingularityFn1),
    cat: SF4Cost(exports.RamCostConstants.SingularityFn1 / 4),
    connect: SF4Cost(exports.RamCostConstants.SingularityFn1),
    manualHack: SF4Cost(exports.RamCostConstants.SingularityFn1),
    installBackdoor: SF4Cost(exports.RamCostConstants.SingularityFn1),
    getDarkwebProgramCost: SF4Cost(exports.RamCostConstants.SingularityFn1 / 4),
    getDarkwebPrograms: SF4Cost(exports.RamCostConstants.SingularityFn1 / 4),
    hospitalize: SF4Cost(exports.RamCostConstants.SingularityFn1 / 4),
    isBusy: SF4Cost(exports.RamCostConstants.SingularityFn1 / 4),
    stopAction: SF4Cost(exports.RamCostConstants.SingularityFn1 / 2),
    upgradeHomeRam: SF4Cost(exports.RamCostConstants.SingularityFn2),
    upgradeHomeCores: SF4Cost(exports.RamCostConstants.SingularityFn2),
    getUpgradeHomeRamCost: SF4Cost(exports.RamCostConstants.SingularityFn2 / 2),
    getUpgradeHomeCoresCost: SF4Cost(exports.RamCostConstants.SingularityFn2 / 2),
    workForCompany: SF4Cost(exports.RamCostConstants.SingularityFn2),
    applyToCompany: SF4Cost(exports.RamCostConstants.SingularityFn2),
    quitJob: SF4Cost(exports.RamCostConstants.SingularityFn2),
    getCompanyRep: SF4Cost(exports.RamCostConstants.SingularityFn2 / 3),
    getCompanyFavor: SF4Cost(exports.RamCostConstants.SingularityFn2 / 3),
    getCompanyFavorGain: SF4Cost(exports.RamCostConstants.SingularityFn2 / 4),
    getFactionInviteRequirements: SF4Cost(exports.RamCostConstants.SingularityFn2),
    getFactionEnemies: SF4Cost(exports.RamCostConstants.SingularityFn2),
    checkFactionInvitations: SF4Cost(exports.RamCostConstants.SingularityFn2),
    joinFaction: SF4Cost(exports.RamCostConstants.SingularityFn2),
    workForFaction: SF4Cost(exports.RamCostConstants.SingularityFn2),
    getFactionWorkTypes: SF4Cost(exports.RamCostConstants.SingularityFn2 / 3),
    getFactionRep: SF4Cost(exports.RamCostConstants.SingularityFn2 / 3),
    getFactionFavor: SF4Cost(exports.RamCostConstants.SingularityFn2 / 3),
    getFactionFavorGain: SF4Cost(exports.RamCostConstants.SingularityFn2 / 4),
    donateToFaction: SF4Cost(exports.RamCostConstants.SingularityFn3),
    createProgram: SF4Cost(exports.RamCostConstants.SingularityFn3),
    getHackingLevelRequirementOfProgram: SF4Cost(exports.RamCostConstants.SingularityFn3),
    commitCrime: SF4Cost(exports.RamCostConstants.SingularityFn3),
    getCrimeChance: SF4Cost(exports.RamCostConstants.SingularityFn3),
    getCrimeStats: SF4Cost(exports.RamCostConstants.SingularityFn3),
    getOwnedAugmentations: SF4Cost(exports.RamCostConstants.SingularityFn3),
    getOwnedSourceFiles: SF4Cost(exports.RamCostConstants.SingularityFn3),
    getAugmentationFactions: SF4Cost(exports.RamCostConstants.SingularityFn3),
    getAugmentationsFromFaction: SF4Cost(exports.RamCostConstants.SingularityFn3),
    getAugmentationPrereq: SF4Cost(exports.RamCostConstants.SingularityFn3),
    getAugmentationPrice: SF4Cost(exports.RamCostConstants.SingularityFn3 / 2),
    getAugmentationBasePrice: SF4Cost(exports.RamCostConstants.SingularityFn3 / 2),
    getAugmentationRepReq: SF4Cost(exports.RamCostConstants.SingularityFn3 / 2),
    getAugmentationStats: SF4Cost(exports.RamCostConstants.SingularityFn3),
    purchaseAugmentation: SF4Cost(exports.RamCostConstants.SingularityFn3),
    softReset: SF4Cost(exports.RamCostConstants.SingularityFn3),
    installAugmentations: SF4Cost(exports.RamCostConstants.SingularityFn3),
    isFocused: SF4Cost(0.1),
    setFocus: SF4Cost(0.1),
    getSaveData: SF4Cost(exports.RamCostConstants.SingularityFn1 / 2),
    exportGame: SF4Cost(exports.RamCostConstants.SingularityFn1 / 2),
    exportGameBonus: SF4Cost(exports.RamCostConstants.SingularityFn1 / 4),
    b1tflum3: SF4Cost(16),
    destroyW0r1dD43m0n: SF4Cost(32),
    getCurrentWork: SF4Cost(0.5),
    getUnlockedAchievements: SF4Cost(exports.RamCostConstants.SingularityFn3),
};
const format = {
    number: 0,
    ram: 0,
    percent: 0,
    time: 0,
};
// Gang API
const gang = {
    createGang: exports.RamCostConstants.GangApiBase / 4,
    inGang: exports.RamCostConstants.GangApiBase / 4,
    getMemberNames: exports.RamCostConstants.GangApiBase / 4,
    renameMember: 0,
    getGangInformation: exports.RamCostConstants.GangApiBase / 2,
    getOtherGangInformation: exports.RamCostConstants.GangApiBase / 2,
    getMemberInformation: exports.RamCostConstants.GangApiBase / 2,
    canRecruitMember: exports.RamCostConstants.GangApiBase / 4,
    getRecruitsAvailable: exports.RamCostConstants.GangApiBase / 4,
    respectForNextRecruit: exports.RamCostConstants.GangApiBase / 4,
    recruitMember: exports.RamCostConstants.GangApiBase / 2,
    getTaskNames: 0,
    getTaskStats: exports.RamCostConstants.GangApiBase / 4,
    setMemberTask: exports.RamCostConstants.GangApiBase / 2,
    getEquipmentNames: 0,
    getEquipmentCost: exports.RamCostConstants.GangApiBase / 2,
    getEquipmentType: exports.RamCostConstants.GangApiBase / 2,
    getEquipmentStats: exports.RamCostConstants.GangApiBase / 2,
    purchaseEquipment: exports.RamCostConstants.GangApiBase,
    ascendMember: exports.RamCostConstants.GangApiBase,
    getAscensionResult: exports.RamCostConstants.GangApiBase / 2,
    getInstallResult: exports.RamCostConstants.GangApiBase / 2,
    setTerritoryWarfare: exports.RamCostConstants.GangApiBase / 2,
    getChanceToWinClash: exports.RamCostConstants.GangApiBase,
    getBonusTime: 0,
    nextUpdate: exports.RamCostConstants.CycleTiming,
};
// Go API
const go = {
    makeMove: 4,
    passTurn: 0,
    getBoardState: 4,
    getMoveHistory: 0,
    getCurrentPlayer: 0,
    getGameState: 0,
    getOpponent: 0,
    opponentNextTurn: 0,
    resetBoardState: 0,
    analysis: {
        getValidMoves: 8,
        getChains: 16,
        getLiberties: 16,
        getControlledEmptyNodes: 16,
        getStats: 0,
        resetStats: 0,
        setTestingBoardState: 4,
        highlightPoint: 0,
        clearPointHighlight: 0,
        clearAllPointHighlights: 0,
    },
    cheat: {
        getCheatSuccessChance: 1,
        getCheatCount: 1,
        removeRouter: 8,
        playTwoMoves: 8,
        repairOfflineNode: 8,
        destroyNode: 8,
    },
};
// Bladeburner API
const bladeburner = {
    inBladeburner: exports.RamCostConstants.BladeburnerApiBase / 4,
    getContractNames: 0,
    getOperationNames: 0,
    getBlackOpNames: 0,
    getNextBlackOp: exports.RamCostConstants.BladeburnerApiBase / 2,
    getBlackOpRank: exports.RamCostConstants.BladeburnerApiBase / 2,
    getGeneralActionNames: 0,
    getSkillNames: 0,
    startAction: exports.RamCostConstants.BladeburnerApiBase,
    stopBladeburnerAction: exports.RamCostConstants.BladeburnerApiBase / 2,
    getCurrentAction: exports.RamCostConstants.BladeburnerApiBase / 4,
    getActionTime: exports.RamCostConstants.BladeburnerApiBase,
    getActionCurrentTime: exports.RamCostConstants.BladeburnerApiBase,
    getActionEstimatedSuccessChance: exports.RamCostConstants.BladeburnerApiBase,
    getActionRepGain: exports.RamCostConstants.BladeburnerApiBase,
    getActionCountRemaining: exports.RamCostConstants.BladeburnerApiBase,
    getActionMaxLevel: exports.RamCostConstants.BladeburnerApiBase,
    getActionCurrentLevel: exports.RamCostConstants.BladeburnerApiBase,
    getActionAutolevel: exports.RamCostConstants.BladeburnerApiBase,
    getActionSuccesses: exports.RamCostConstants.BladeburnerApiBase,
    setActionAutolevel: exports.RamCostConstants.BladeburnerApiBase,
    setActionLevel: exports.RamCostConstants.BladeburnerApiBase,
    getRank: exports.RamCostConstants.BladeburnerApiBase,
    getSkillPoints: exports.RamCostConstants.BladeburnerApiBase,
    getSkillLevel: exports.RamCostConstants.BladeburnerApiBase,
    getSkillUpgradeCost: exports.RamCostConstants.BladeburnerApiBase,
    upgradeSkill: exports.RamCostConstants.BladeburnerApiBase,
    getTeamSize: exports.RamCostConstants.BladeburnerApiBase,
    setTeamSize: exports.RamCostConstants.BladeburnerApiBase,
    getCityEstimatedPopulation: exports.RamCostConstants.BladeburnerApiBase,
    getCityCommunities: exports.RamCostConstants.BladeburnerApiBase,
    getCityChaos: exports.RamCostConstants.BladeburnerApiBase,
    getCity: exports.RamCostConstants.BladeburnerApiBase,
    switchCity: exports.RamCostConstants.BladeburnerApiBase,
    getStamina: exports.RamCostConstants.BladeburnerApiBase,
    joinBladeburnerFaction: exports.RamCostConstants.BladeburnerApiBase,
    joinBladeburnerDivision: exports.RamCostConstants.BladeburnerApiBase,
    getBonusTime: 0,
    nextUpdate: exports.RamCostConstants.CycleTiming,
};
const infiltration = {
    getPossibleLocations: 0,
    getInfiltration: exports.RamCostConstants.InfiltrationGetInfiltrations,
};
// Coding Contract API
const codingcontract = {
    attempt: exports.RamCostConstants.CodingContractBase,
    getContractType: exports.RamCostConstants.CodingContractBase / 2,
    getData: exports.RamCostConstants.CodingContractBase / 2,
    getContract: exports.RamCostConstants.CodingContractBase * (3 / 2),
    getDescription: exports.RamCostConstants.CodingContractBase / 2,
    getNumTriesRemaining: exports.RamCostConstants.CodingContractBase / 5,
    createDummyContract: exports.RamCostConstants.CodingContractBase / 5,
    getContractTypes: 0,
};
// Duplicate Sleeve API
const sleeve = {
    getNumSleeves: exports.RamCostConstants.SleeveBase,
    setToIdle: exports.RamCostConstants.SleeveBase,
    setToShockRecovery: exports.RamCostConstants.SleeveBase,
    setToSynchronize: exports.RamCostConstants.SleeveBase,
    setToCommitCrime: exports.RamCostConstants.SleeveBase,
    setToUniversityCourse: exports.RamCostConstants.SleeveBase,
    travel: exports.RamCostConstants.SleeveBase,
    setToCompanyWork: exports.RamCostConstants.SleeveBase,
    setToFactionWork: exports.RamCostConstants.SleeveBase,
    setToGymWorkout: exports.RamCostConstants.SleeveBase,
    getTask: exports.RamCostConstants.SleeveBase,
    getSleeve: exports.RamCostConstants.SleeveBase,
    getSleeveAugmentations: exports.RamCostConstants.SleeveBase,
    getSleevePurchasableAugs: exports.RamCostConstants.SleeveBase,
    purchaseSleeveAug: exports.RamCostConstants.SleeveBase,
    setToBladeburnerAction: exports.RamCostConstants.SleeveBase,
    getSleeveAugmentationPrice: exports.RamCostConstants.SleeveBase,
    getSleeveAugmentationRepReq: exports.RamCostConstants.SleeveBase,
};
// Stanek API
const stanek = {
    giftWidth: exports.RamCostConstants.StanekWidth,
    giftHeight: exports.RamCostConstants.StanekHeight,
    chargeFragment: exports.RamCostConstants.StanekCharge,
    fragmentDefinitions: exports.RamCostConstants.StanekFragmentDefinitions,
    activeFragments: exports.RamCostConstants.StanekPlacedFragments,
    clearGift: exports.RamCostConstants.StanekClear,
    canPlaceFragment: exports.RamCostConstants.StanekCanPlace,
    placeFragment: exports.RamCostConstants.StanekPlace,
    getFragment: exports.RamCostConstants.StanekFragmentAt,
    removeFragment: exports.RamCostConstants.StanekDeleteAt,
    acceptGift: exports.RamCostConstants.StanekAcceptGift,
};
// UI API
const ui = {
    openTail: 0,
    renderTail: 0,
    moveTail: 0,
    resizeTail: 0,
    closeTail: 0,
    setTailTitle: 0,
    setTailFontSize: 0,
    getTheme: 0,
    setTheme: 0,
    resetTheme: 0,
    getStyles: 0,
    setStyles: 0,
    resetStyles: 0,
    getGameInfo: 0,
    clearTerminal: 0,
    windowSize: 0,
};
// Grafting API
const grafting = {
    getAugmentationGraftPrice: 3.75,
    getAugmentationGraftTime: 3.75,
    getGraftableAugmentations: 5,
    graftAugmentation: 7.5,
    waitForOngoingGrafting: 1,
};
const corporation = {
    hasCorporation: 0,
    canCreateCorporation: 0,
    createCorporation: exports.RamCostConstants.CorporationAction,
    hasUnlock: exports.RamCostConstants.CorporationInfo,
    getUnlockCost: exports.RamCostConstants.CorporationInfo,
    getUpgradeLevel: exports.RamCostConstants.CorporationInfo,
    getUpgradeLevelCost: exports.RamCostConstants.CorporationInfo,
    getInvestmentOffer: exports.RamCostConstants.CorporationInfo,
    getConstants: 0,
    getIndustryData: exports.RamCostConstants.CorporationInfo,
    getMaterialData: exports.RamCostConstants.CorporationInfo,
    acceptInvestmentOffer: exports.RamCostConstants.CorporationAction,
    goPublic: exports.RamCostConstants.CorporationAction,
    bribe: exports.RamCostConstants.CorporationAction,
    getCorporation: exports.RamCostConstants.CorporationInfo,
    getDivision: exports.RamCostConstants.CorporationInfo,
    expandIndustry: exports.RamCostConstants.CorporationAction,
    expandCity: exports.RamCostConstants.CorporationAction,
    purchaseUnlock: exports.RamCostConstants.CorporationAction,
    levelUpgrade: exports.RamCostConstants.CorporationAction,
    issueDividends: exports.RamCostConstants.CorporationAction,
    issueNewShares: exports.RamCostConstants.CorporationAction,
    buyBackShares: exports.RamCostConstants.CorporationAction,
    sellShares: exports.RamCostConstants.CorporationAction,
    getBonusTime: 0,
    nextUpdate: exports.RamCostConstants.CycleTiming,
    sellDivision: exports.RamCostConstants.CorporationAction,
    // Warehouse API
    sellMaterial: exports.RamCostConstants.CorporationAction,
    sellProduct: exports.RamCostConstants.CorporationAction,
    discontinueProduct: exports.RamCostConstants.CorporationAction,
    setSmartSupply: exports.RamCostConstants.CorporationAction,
    setSmartSupplyOption: exports.RamCostConstants.CorporationAction,
    buyMaterial: exports.RamCostConstants.CorporationAction,
    bulkPurchase: exports.RamCostConstants.CorporationAction,
    getWarehouse: exports.RamCostConstants.CorporationInfo,
    getProduct: exports.RamCostConstants.CorporationInfo,
    getMaterial: exports.RamCostConstants.CorporationInfo,
    setMaterialMarketTA1: exports.RamCostConstants.CorporationAction,
    setMaterialMarketTA2: exports.RamCostConstants.CorporationAction,
    setProductMarketTA1: exports.RamCostConstants.CorporationAction,
    setProductMarketTA2: exports.RamCostConstants.CorporationAction,
    exportMaterial: exports.RamCostConstants.CorporationAction,
    cancelExportMaterial: exports.RamCostConstants.CorporationAction,
    purchaseWarehouse: exports.RamCostConstants.CorporationAction,
    upgradeWarehouse: exports.RamCostConstants.CorporationAction,
    makeProduct: exports.RamCostConstants.CorporationAction,
    limitMaterialProduction: exports.RamCostConstants.CorporationAction,
    limitProductProduction: exports.RamCostConstants.CorporationAction,
    getUpgradeWarehouseCost: exports.RamCostConstants.CorporationInfo,
    hasWarehouse: exports.RamCostConstants.CorporationInfo,
    // Warehouse API
    hireEmployee: exports.RamCostConstants.CorporationAction,
    upgradeOfficeSize: exports.RamCostConstants.CorporationAction,
    throwParty: exports.RamCostConstants.CorporationAction,
    buyTea: exports.RamCostConstants.CorporationAction,
    hireAdVert: exports.RamCostConstants.CorporationAction,
    research: exports.RamCostConstants.CorporationAction,
    getOffice: exports.RamCostConstants.CorporationInfo,
    getHireAdVertCost: exports.RamCostConstants.CorporationInfo,
    getHireAdVertCount: exports.RamCostConstants.CorporationInfo,
    getResearchCost: exports.RamCostConstants.CorporationInfo,
    hasResearched: exports.RamCostConstants.CorporationInfo,
    setJobAssignment: exports.RamCostConstants.CorporationAction,
    getOfficeSizeUpgradeCost: exports.RamCostConstants.CorporationInfo,
};
/** RamCosts guaranteed to match ns structure 1:1 (aside from args and enums).
 *  An error will be generated if there are missing OR additional ram costs defined.
 *  To avoid errors, define every function in NetscriptDefinition.d.ts and NetscriptFunctions,
 *  and have a ram cost associated here. */
exports.RamCosts = {
    corporation,
    hacknet,
    stock,
    singularity,
    format,
    gang,
    go,
    bladeburner,
    infiltration,
    codingcontract,
    sleeve,
    stanek,
    ui,
    grafting,
    sprintf: 0,
    vsprintf: 0,
    scan: exports.RamCostConstants.Scan,
    hack: exports.RamCostConstants.Hack,
    hackAnalyzeThreads: exports.RamCostConstants.HackAnalyze,
    hackAnalyze: exports.RamCostConstants.HackAnalyze,
    hackAnalyzeSecurity: exports.RamCostConstants.HackAnalyze,
    hackAnalyzeChance: exports.RamCostConstants.HackAnalyze,
    sleep: 0,
    asleep: 0,
    share: 2.4,
    getSharePower: 0.2,
    grow: exports.RamCostConstants.Grow,
    growthAnalyze: exports.RamCostConstants.GrowthAnalyze,
    growthAnalyzeSecurity: exports.RamCostConstants.GrowthAnalyze,
    weaken: exports.RamCostConstants.Weaken,
    weakenAnalyze: exports.RamCostConstants.WeakenAnalyze,
    print: 0,
    printf: 0,
    tprint: 0,
    tprintf: 0,
    clearLog: 0,
    disableLog: 0,
    enableLog: 0,
    isLogEnabled: 0,
    getScriptLogs: 0,
    hasTorRouter: 0.05,
    nuke: exports.RamCostConstants.PortProgram,
    brutessh: exports.RamCostConstants.PortProgram,
    ftpcrack: exports.RamCostConstants.PortProgram,
    relaysmtp: exports.RamCostConstants.PortProgram,
    httpworm: exports.RamCostConstants.PortProgram,
    sqlinject: exports.RamCostConstants.PortProgram,
    run: exports.RamCostConstants.Run,
    exec: exports.RamCostConstants.Exec,
    spawn: exports.RamCostConstants.Spawn,
    self: 0,
    kill: exports.RamCostConstants.Kill,
    killall: exports.RamCostConstants.Kill,
    exit: 0,
    atExit: 0,
    scp: exports.RamCostConstants.Scp,
    ls: exports.RamCostConstants.Scan,
    ps: exports.RamCostConstants.Scan,
    getRecentScripts: exports.RamCostConstants.RecentScripts,
    hasRootAccess: exports.RamCostConstants.HasRootAccess,
    getHostname: exports.RamCostConstants.GetHostname,
    getIP: exports.RamCostConstants.GetHostname,
    getHackingLevel: exports.RamCostConstants.GetHackingLevel,
    getHackingMultipliers: 0.25,
    getHacknetMultipliers: 0.25,
    getBitNodeMultipliers: 4,
    getServer: 2,
    getServerMoneyAvailable: exports.RamCostConstants.GetServer,
    getServerSecurityLevel: exports.RamCostConstants.GetServer,
    getServerBaseSecurityLevel: exports.RamCostConstants.GetServer,
    getServerMinSecurityLevel: exports.RamCostConstants.GetServer,
    getServerRequiredHackingLevel: exports.RamCostConstants.GetServer,
    getServerMaxMoney: exports.RamCostConstants.GetServer,
    getServerGrowth: exports.RamCostConstants.GetServer,
    getServerNumPortsRequired: exports.RamCostConstants.GetServer,
    getServerMaxRam: exports.RamCostConstants.GetServerMaxRam,
    getServerUsedRam: exports.RamCostConstants.GetServerUsedRam,
    dnsLookup: 0.05,
    serverExists: exports.RamCostConstants.GetServer,
    fileExists: exports.RamCostConstants.FileExists,
    isRunning: exports.RamCostConstants.IsRunning,
    getPurchasedServerLimit: exports.RamCostConstants.GetPurchasedServerLimit,
    getPurchasedServerMaxRam: exports.RamCostConstants.GetPurchasedServerMaxRam,
    getPurchasedServerCost: exports.RamCostConstants.GetPurchaseServer,
    getPurchasedServerUpgradeCost: 0.1,
    getPurchasedServers: 1.05,
    upgradePurchasedServer: 0.25,
    renamePurchasedServer: 0,
    purchaseServer: exports.RamCostConstants.PurchaseServer,
    deleteServer: exports.RamCostConstants.PurchaseServer,
    write: 0,
    tryWritePort: 0,
    read: 0,
    getFileMetadata: 0,
    peek: 0,
    clear: 0,
    writePort: 0,
    nextPortWrite: 0,
    readPort: 0,
    getPortHandle: 0,
    rm: exports.RamCostConstants.ReadWrite,
    scriptRunning: exports.RamCostConstants.ArbScript,
    scriptKill: exports.RamCostConstants.ArbScript,
    getScriptName: 0,
    getScriptRam: exports.RamCostConstants.GetScript,
    getHackTime: exports.RamCostConstants.GetHackTime,
    getGrowTime: exports.RamCostConstants.GetHackTime,
    getWeakenTime: exports.RamCostConstants.GetHackTime,
    getTotalScriptIncome: exports.RamCostConstants.GetScript,
    getScriptIncome: exports.RamCostConstants.GetScript,
    getTotalScriptExpGain: exports.RamCostConstants.GetScript,
    getScriptExpGain: exports.RamCostConstants.GetScript,
    getRunningScript: exports.RamCostConstants.GetRunningScript,
    ramOverride: 0,
    prompt: 0,
    wget: 0,
    getFavorToDonate: exports.RamCostConstants.GetFavorToDonate,
    getPlayer: exports.RamCostConstants.SingularityFn1 / 4,
    getMoneySources: exports.RamCostConstants.GetMoneySourcesCost,
    mv: 0,
    getResetInfo: 1,
    getFunctionRamCost: 0,
    toast: 0,
    clearPort: 0,
    openDevMenu: 0,
    alert: 0,
    flags: 0,
    exploit: 0,
    bypass: 0,
    alterReality: 0,
    rainbow: 0,
    heart: { break: 0 },
    tprintRaw: 0,
    printRaw: 0,
    dynamicImport: 0,
    formulas: {
        mockServer: 0,
        mockPlayer: 0,
        mockPerson: 0,
        reputation: {
            calculateFavorToRep: 0,
            calculateRepToFavor: 0,
            repFromDonation: 0,
            donationForRep: 0,
            sharePower: 0,
        },
        skills: {
            calculateSkill: 0,
            calculateExp: 0,
        },
        hacking: {
            hackChance: 0,
            hackExp: 0,
            hackPercent: 0,
            growPercent: 0,
            growThreads: 0,
            growAmount: 0,
            hackTime: 0,
            growTime: 0,
            weakenTime: 0,
        },
        hacknetNodes: {
            moneyGainRate: 0,
            levelUpgradeCost: 0,
            ramUpgradeCost: 0,
            coreUpgradeCost: 0,
            hacknetNodeCost: 0,
            constants: 0,
        },
        hacknetServers: {
            hashGainRate: 0,
            levelUpgradeCost: 0,
            ramUpgradeCost: 0,
            coreUpgradeCost: 0,
            cacheUpgradeCost: 0,
            hashUpgradeCost: 0,
            hacknetServerCost: 0,
            constants: 0,
        },
        gang: {
            wantedPenalty: 0,
            respectGain: 0,
            wantedLevelGain: 0,
            moneyGain: 0,
            ascensionPointsGain: 0,
            ascensionMultiplier: 0,
        },
        work: {
            crimeSuccessChance: 0,
            crimeGains: 0,
            gymGains: 0,
            universityGains: 0,
            factionGains: 0,
            companyGains: 0,
        },
        bladeburner: {
            skillMaxUpgradeCount: 0,
        },
    },
};
function getRamCost(tree, throwOnUndefined = false) {
    if (tree.length === 0)
        throw new Error(`No arguments passed to getRamCost()`);
    let obj = exports.RamCosts;
    for (const branch of tree) {
        const next = obj[branch];
        if (next === undefined) {
            // If no ram cost is defined (e.g. for removed functions), the cost is 0.
            const errorText = `No ram cost is defined for (ns.${tree.join(".")})`;
            if (throwOnUndefined)
                throw errorText;
            return 0;
        }
        if (next && typeof next === "object") {
            obj = next;
            continue;
        }
        return typeof next === "function" ? next() : next;
    }
    throw new Error(`Tried to get ram cost for ns.${tree.join(".")} but the value was an invalid type`);
}
