import { Output, Link, RawOutput, TTimer } from "./OutputTypes";
import { BaseServer } from "../Server/BaseServer";
import { TextFile } from "../TextFile";
import { Script } from "../Script/Script";
import { Directory } from "../Paths/Directory";
import { FilePath } from "../Paths/FilePath";
import { ContractFilePath } from "../Paths/ContractFilePath";
export declare const TerminalCommands: Record<string, (args: (string | number | boolean)[], server: BaseServer) => void>;
export declare class Terminal {
    action: TTimer | null;
    commandHistory: string[];
    commandHistoryIndex: number;
    outputHistory: (Output | Link | RawOutput)[];
    contractOpen: boolean;
    currDir: Directory;
    process(cycles: number): void;
    append(item: Output | Link | RawOutput): void;
    print(s: string): void;
    printRaw(node: React.ReactNode): void;
    error(s: string): void;
    success(s: string): void;
    info(s: string): void;
    warn(s: string): void;
    startHack(): void;
    startGrow(): void;
    startWeaken(): void;
    startBackdoor(): void;
    startAnalyze(): void;
    startAction(n: number, action: "h" | "b" | "a" | "g" | "w", server?: BaseServer): void;
    finishHack(server: BaseServer, cancelled?: boolean): void;
    finishGrow(server: BaseServer, cancelled?: boolean): void;
    finishWeaken(server: BaseServer, cancelled?: boolean): void;
    finishBackdoor(server: BaseServer, cancelled?: boolean): void;
    finishAnalyze(currServ: BaseServer, cancelled?: boolean): void;
    finishAction(cancelled?: boolean): void;
    getFile(filename: string): Script | TextFile | string | null;
    getFilepath(path: string, useAbsolute?: boolean): FilePath | null;
    getDirectory(path: string, useAbsolute?: boolean): Directory | null;
    getScript(filename: string): Script | null;
    getTextFile(filename: string): TextFile | null;
    getLitFile(filename: string): string | null;
    cwd(): Directory;
    setcwd(dir: Directory): void;
    runContract(contractPath: ContractFilePath): Promise<void>;
    executeScanAnalyzeCommand(depth?: number, all?: boolean): void;
    connectToServer(hostname: string, singularity?: boolean): void;
    executeCommands(commands: string): void;
    clear(): void;
    prestige(): void;
    executeCommand(command: string): void;
    getProgressText(): string;
}
