import { GangMemberTask } from "./GangMemberTask";
import { GangMemberUpgrade } from "./GangMemberUpgrade";
import { IAscensionResult } from "./IAscensionResult";
import { Gang } from "./Gang";
import { IReviverValue } from "../utils/JSONReviver";
import { GangMemberExpGain } from "@nsdefs";
interface IMults {
    hack: number;
    str: number;
    def: number;
    dex: number;
    agi: number;
    cha: number;
}
export declare class GangMember {
    name: string;
    task: string;
    earnedRespect: number;
    hack: number;
    str: number;
    def: number;
    dex: number;
    agi: number;
    cha: number;
    hack_exp: number;
    str_exp: number;
    def_exp: number;
    dex_exp: number;
    agi_exp: number;
    cha_exp: number;
    hack_mult: number;
    str_mult: number;
    def_mult: number;
    dex_mult: number;
    agi_mult: number;
    cha_mult: number;
    hack_asc_points: number;
    str_asc_points: number;
    def_asc_points: number;
    dex_asc_points: number;
    agi_asc_points: number;
    cha_asc_points: number;
    upgrades: string[];
    augmentations: string[];
    constructor(name?: string);
    calculateSkill(exp: number, mult?: number): number;
    calculateAscensionMult(points: number): number;
    updateSkillLevels(): void;
    calculatePower(): number;
    assignToTask(taskName: string): boolean;
    unassignFromTask(): void;
    getTask(): GangMemberTask;
    calculateRespectGain(gang: Gang): number;
    calculateWantedLevelGain(gang: Gang): number;
    calculateMoneyGain(gang: Gang): number;
    expMult(): IMults;
    calculateExpGain(numCycles?: number): GangMemberExpGain | null;
    gainExperience(numCycles: number): void;
    earnRespect(numCycles: number, gang: Gang): number;
    getGainedAscensionPoints(): IMults;
    canAscend(): boolean;
    getCurrentAscensionMults(): IMults;
    getAscensionMultsAfterAscend(): IMults;
    getAscensionResults(): IMults;
    getPostInstallPoints(): IMults;
    ascend(): IAscensionResult;
    applyUpgrade(upg: GangMemberUpgrade): void;
    buyUpgrade(upg: GangMemberUpgrade): boolean;
    /** Serialize the current object to a JSON save state. */
    toJSON(): IReviverValue;
    /** Initializes a GangMember object from a JSON save state. */
    static fromJSON(value: IReviverValue): GangMember;
}
export {};
