"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KEY = void 0;
/** Values of keyboard event key returned by event.key */
var KEY;
(function (KEY) {
    KEY["ENTER"] = "Enter";
    KEY["ESC"] = "Escape";
    KEY["TAB"] = "Tab";
    KEY["SPACE"] = " ";
    KEY["BACKSPACE"] = "Backspace";
    KEY["UP_ARROW"] = "ArrowUp";
    KEY["DOWN_ARROW"] = "ArrowDown";
    KEY["LEFT_ARROW"] = "ArrowLeft";
    KEY["RIGHT_ARROW"] = "ArrowRight";
    KEY["QUOTE"] = "'";
    KEY["DOUBLE_QUOTE"] = "\"";
    KEY["OPEN_BRACKET"] = "[";
    KEY["CLOSE_BRACKET"] = "]";
    KEY["LESS_THAN"] = "<";
    KEY["GREATER_THAN"] = ">";
    KEY["OPEN_PARENTHESIS"] = "(";
    KEY["CLOSE_PARENTHESIS"] = ")";
    KEY["OPEN_BRACE"] = "{";
    KEY["CLOSE_BRACE"] = "}";
    KEY["EQUAL"] = "=";
    KEY["PIPE"] = "|";
    KEY["DOT"] = ".";
    KEY["FORWARD_SLASH"] = "/";
    KEY["HYPHEN"] = "-";
    KEY["HASH"] = "#";
    KEY["k0"] = "0";
    KEY["k1"] = "1";
    KEY["k2"] = "2";
    KEY["k3"] = "3";
    KEY["k4"] = "4";
    KEY["k5"] = "5";
    KEY["k6"] = "6";
    KEY["k7"] = "7";
    KEY["k8"] = "8";
    KEY["k9"] = "9";
    KEY["A"] = "a";
    KEY["B"] = "b";
    KEY["C"] = "c";
    KEY["D"] = "d";
    KEY["E"] = "e";
    KEY["F"] = "f";
    KEY["G"] = "g";
    KEY["H"] = "h";
    KEY["I"] = "i";
    KEY["J"] = "j";
    KEY["K"] = "k";
    KEY["L"] = "l";
    KEY["M"] = "m";
    KEY["N"] = "n";
    KEY["O"] = "o";
    KEY["P"] = "p";
    KEY["Q"] = "q";
    KEY["R"] = "r";
    KEY["S"] = "s";
    KEY["T"] = "t";
    KEY["U"] = "u";
    KEY["V"] = "v";
    KEY["W"] = "w";
    KEY["X"] = "x";
    KEY["Y"] = "y";
    KEY["Z"] = "z";
})(KEY || (exports.KEY = KEY = {}));
