"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CompanyName = void 0;
var CompanyName;
(function (CompanyName) {
    CompanyName["ECorp"] = "ECorp";
    CompanyName["MegaCorp"] = "MegaCorp";
    CompanyName["BachmanAndAssociates"] = "Bachman & Associates";
    CompanyName["BladeIndustries"] = "Blade Industries";
    CompanyName["NWO"] = "NWO";
    CompanyName["ClarkeIncorporated"] = "Clarke Incorporated";
    CompanyName["OmniTekIncorporated"] = "OmniTek Incorporated";
    CompanyName["FourSigma"] = "Four Sigma";
    CompanyName["KuaiGongInternational"] = "KuaiGong International";
    CompanyName["FulcrumTechnologies"] = "Fulcrum Technologies";
    CompanyName["StormTechnologies"] = "Storm Technologies";
    CompanyName["DefComm"] = "DefComm";
    CompanyName["HeliosLabs"] = "Helios Labs";
    CompanyName["VitaLife"] = "VitaLife";
    CompanyName["IcarusMicrosystems"] = "Icarus Microsystems";
    CompanyName["UniversalEnergy"] = "Universal Energy";
    CompanyName["GalacticCybersystems"] = "Galactic Cybersystems";
    CompanyName["AeroCorp"] = "AeroCorp";
    CompanyName["OmniaCybersystems"] = "Omnia Cybersystems";
    CompanyName["SolarisSpaceSystems"] = "Solaris Space Systems";
    CompanyName["DeltaOne"] = "DeltaOne";
    CompanyName["GlobalPharmaceuticals"] = "Global Pharmaceuticals";
    CompanyName["NovaMedical"] = "Nova Medical";
    CompanyName["CIA"] = "Central Intelligence Agency";
    CompanyName["NSA"] = "National Security Agency";
    CompanyName["WatchdogSecurity"] = "Watchdog Security";
    CompanyName["LexoCorp"] = "LexoCorp";
    CompanyName["RhoConstruction"] = "Rho Construction";
    CompanyName["AlphaEnterprises"] = "Alpha Enterprises";
    CompanyName["Police"] = "Aevum Police Headquarters";
    CompanyName["SysCoreSecurities"] = "SysCore Securities";
    CompanyName["CompuTek"] = "CompuTek";
    CompanyName["NetLinkTechnologies"] = "NetLink Technologies";
    CompanyName["CarmichaelSecurity"] = "Carmichael Security";
    CompanyName["FoodNStuff"] = "FoodNStuff";
    CompanyName["JoesGuns"] = "Joe's Guns";
    CompanyName["OmegaSoftware"] = "Omega Software";
    CompanyName["NoodleBar"] = "Noodle Bar";
})(CompanyName || (exports.CompanyName = CompanyName = {}));
