export interface Multipliers {
    hacking_chance: number;
    hacking_speed: number;
    hacking_money: number;
    hacking_grow: number;
    hacking: number;
    hacking_exp: number;
    strength: number;
    strength_exp: number;
    defense: number;
    defense_exp: number;
    dexterity: number;
    dexterity_exp: number;
    agility: number;
    agility_exp: number;
    charisma: number;
    charisma_exp: number;
    hacknet_node_money: number;
    hacknet_node_purchase_cost: number;
    hacknet_node_ram_cost: number;
    hacknet_node_core_cost: number;
    hacknet_node_level_cost: number;
    company_rep: number;
    faction_rep: number;
    work_money: number;
    crime_success: number;
    crime_money: number;
    bladeburner_max_stamina: number;
    bladeburner_stamina_gain: number;
    bladeburner_analysis: number;
    bladeburner_success_chance: number;
}
export declare const defaultMultipliers: () => Multipliers;
export declare const mergeMultipliers: (m0: Multipliers, m1: Multipliers) => Multipliers;
export declare const scaleMultipliers: (m0: Multipliers, v: number) => Multipliers;
